// emojiMap.js
export const emojiMap = {
  // Smileys & Emotion
  smile: "😄",
  grin: "😁",
  joy: "😂",
  rofl: "🤣",
  relaxed: "☺️",
  blush: "😊",
  wink: "😉",
  heart_eyes: "😍",
  kissing_heart: "😘",
  thinking: "🤔",
  neutral_face: "😐",
  expressionless: "😑",
  unamused: "😒",
  sweat_smile: "😅",
  cry: "😢",
  sob: "😭",
  angry: "😠",
  rage: "😡",
  sleepy: "😴",
  disappointed: "😞",
  fearful: "😨",
  shocked: "😱",
  // People & Body
  thumbsup: "👍",
  thumbsdown: "👎",
  clap: "👏",
  wave: "👋",
  pray: "🙏",
  ok_hand: "👌",
  punch: "👊",
  // Animals & Nature
  dog: "🐶",
  cat: "🐱",
  mouse: "🐭",
  rabbit: "🐰",
  fox: "🦊",
  bear: "🐻",
  panda: "🐼",
  tiger: "🐯",
  lion: "🦁",
  dragon: "🐉",
  // Food & Drink
  pizza: "🍕",
  burger: "🍔",
  fries: "🍟",
  taco: "🌮",
  ice_cream: "🍨",
  cake: "🍰",
  coffee: "☕",
  beer: "🍺",
  wine: "🍷",
  // Activities & Travel
  soccer: "⚽",
  basketball: "🏀",
  baseball: "⚾",
  football: "🏈",
  trophy: "🏆",
  airplane: "✈️",
  car: "🚗",
  train: "🚆",
  ship: "🚢",
  // Objects & Symbols
  fire: "🔥",
  star: "⭐",
  heart: "❤️",
  sparkles: "✨",
  sun: "☀️",
  moon: "🌙",
  cloud: "☁️",
  umbrella: "☂️",
  snowflake: "❄️",
  // Flags
  us: "🇺🇸",
  gb: "🇬🇧",
  de: "🇩🇪",
  fr: "🇫🇷",
  jp: "🇯🇵",
  kr: "🇰🇷",
  cn: "🇨🇳",
  ru: "🇷🇺",
  ae: "🇦🇪",
  // Fun / Misc
  poop: "💩",
  party: "🥳",
  alien: "👽",
  robot: "🤖",
  ghost: "👻",
  skull: "💀",
  rainbow: "🌈",
  sparkler: "🎇",
  // Add more as needed…
};
